email.emailAddress=speech.mailing@gmail.com
email.emailPassword=twkfakoreejvzfwk

hibernate.connection.url=jdbc:postgresql://localhost:5432/travel
hibernate.connection.username=postgres
hibernate.connection.password=214167